"""Generated Protocol Buffers bindings for wavetable metadata.

This module contains the generated protobuf classes from wavetable.proto.
The bindings are generated using the protoc compiler.

To regenerate bindings, run from the wtgen project root:
    protoc --python_out=src/wtgen/format/proto \\
           --proto_path=../../proto \\
           ../../proto/wavetable.proto

Note: The wavetable_pb2.py file is auto-generated and should not be manually edited.
"""

# Import the generated protobuf module
# The actual wavetable_pb2.py is generated by protoc
try:
    from wtgen.format.proto.wavetable_pb2 import (
        ClassicDigitalMetadata,
        HighResolutionMetadata,
        InterpolationHint,
        NormalizationMethod,
        PcmSampleMetadata,
        VintageEmulationMetadata,
        WavetableMetadata,
        WavetableType,
    )

    __all__ = [
        "WavetableMetadata",
        "WavetableType",
        "NormalizationMethod",
        "InterpolationHint",
        "ClassicDigitalMetadata",
        "HighResolutionMetadata",
        "VintageEmulationMetadata",
        "PcmSampleMetadata",
    ]
except ImportError:
    # Proto files not yet generated - provide helpful error message
    import sys

    print(
        "Warning: wavetable_pb2.py not found. Generate it with:\n"
        "  cd projects/wtgen && protoc --python_out=src/wtgen/format/proto "
        "--proto_path=../../proto ../../proto/wavetable.proto",
        file=sys.stderr,
    )
    raise
